# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Server
source: ./
destination: ./_gh_pages
host:           0.0.0.0
port:           9001
baseurl: /
url:            "https://alfonsodev.github.io"
encoding:       UTF-8

remote-theme: wowthemesnet/mediumish-theme-jekyll