# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Server
source: "site"
destination: ./_gh_pages
host:           0.0.0.0
port:           9001
baseurl:        "/"
url:            "https://alfonsodev.github.io"
encoding:       UTF-8

theme: jekyll-theme-hacker